import PRChecksC

/-! `#print axioms` for every theorem of PRChecksC (run: `lake env lean Axioms.lean`). -/

#print axioms PRChecksC.exponent_certificate
#print axioms PRChecksC.exp_le_inv_one_sub
#print axioms PRChecksC.moment_term
#print axioms PRChecksC.singleton_form
#print axioms PRChecksC.neglog_bounds
#print axioms PRChecksC.log_inv_le
#print axioms PRChecksC.neglog_eq
#print axioms PRChecksC.log_two_eq
#print axioms PRChecksC.log_three_eq
#print axioms PRChecksC.log_five_eq
#print axioms PRChecksC.log_two_bounds
#print axioms PRChecksC.log_three_bounds
#print axioms PRChecksC.log_five_bounds
#print axioms PRChecksC.log_21952_lt
#print axioms PRChecksC.log_28_lt
#print axioms PRChecksC.log_30_lt
#print axioms PRChecksC.log_27000_lt
#print axioms PRChecksC.taylor_six_fifths
#print axioms PRChecksC.PR9.roles
#print axioms PRChecksC.PR9.bit_counts
#print axioms PRChecksC.PR9.bit_eta
#print axioms PRChecksC.PR9.bit_log
#print axioms PRChecksC.PR9.bit_exponent
#print axioms PRChecksC.PR9.complex_counts
#print axioms PRChecksC.PR9.complex_eta
#print axioms PRChecksC.PR9.complex_exponent
#print axioms PRChecksC.PR9.guard_constants
#print axioms PRChecksC.PR9.parameter_origin
#print axioms PRChecksC.PR9.recurrence_values
#print axioms PRChecksC.PR9.slack_values
#print axioms PRChecksC.PR9.constraints_strict
#print axioms PRChecksC.PR9.margin_values
#print axioms PRChecksC.PR9.kappa_witness
#print axioms PRChecksC.PR10.bit_counts
#print axioms PRChecksC.PR10.bit_eta
#print axioms PRChecksC.PR10.bit_classes
#print axioms PRChecksC.PR10.bit_singletons
#print axioms PRChecksC.PR10.data_rank_sum
#print axioms PRChecksC.PR10.bit_weights
#print axioms PRChecksC.PR10.bit_logs
#print axioms PRChecksC.PR10.bit_moment_upper
#print axioms PRChecksC.PR10.bit_moment
#print axioms PRChecksC.PR10.bit_moment_177
#print axioms PRChecksC.PR10.complex_counts
#print axioms PRChecksC.PR10.complex_weights
#print axioms PRChecksC.PR10.complex_logs
#print axioms PRChecksC.PR10.complex_moment_upper
#print axioms PRChecksC.PR10.complex_moment
#print axioms PRChecksC.PR10.guard_constants
#print axioms PRChecksC.PR10.path_moment_rational
#print axioms PRChecksC.PR10.m_rho_gt
#print axioms PRChecksC.PR10.path_moments
#print axioms PRChecksC.PR10.leaf_absorption
#print axioms PRChecksC.PR10.internal_step
#print axioms PRChecksC.PR10.parameter_origin
#print axioms PRChecksC.PR10.patch_exponents
#print axioms PRChecksC.PR10.recurrence_values
#print axioms PRChecksC.PR10.slack_values
#print axioms PRChecksC.PR10.constraints_strict
#print axioms PRChecksC.PR10.margin_values
#print axioms PRChecksC.PR10.kappa_witness
#print axioms PRChecksC.PR11.certified_saving_le
#print axioms PRChecksC.PR11.saving_reject
#print axioms PRChecksC.PR11.log_13824_ge
#print axioms PRChecksC.PR11.log_19683_ge
#print axioms PRChecksC.PR11.log_27000_ge
#print axioms PRChecksC.PR11.log_8000_ge
#print axioms PRChecksC.PR11.log_mono
#print axioms PRChecksC.PR11.screen_eta
#print axioms PRChecksC.PR11.screen_ratio
#print axioms PRChecksC.PR11.screens_reject
#print axioms PRChecksC.PR11.q5_nonpositive
#print axioms PRChecksC.PR11.q5_rows
#print axioms PRChecksC.PR11.log_cube_ge
#print axioms PRChecksC.PR11.q5_tail
#print axioms PRChecksC.PR11.q7_all
#print axioms PRChecksC.PR11.family_binomials
#print axioms PRChecksC.PR12.bit_counts
#print axioms PRChecksC.PR12.bit_eta
#print axioms PRChecksC.PR12.bit_classes
#print axioms PRChecksC.PR12.bit_weights
#print axioms PRChecksC.PR12.bit_logs
#print axioms PRChecksC.PR12.bit_moment_upper
#print axioms PRChecksC.PR12.bit_moment_upper_254_fails
#print axioms PRChecksC.PR12.bit_moment
#print axioms PRChecksC.PR12.proof_tex_numbers
#print axioms PRChecksC.PR12.parameter_origin
#print axioms PRChecksC.PR12.patch_exponents
#print axioms PRChecksC.PR12.recurrence_values
#print axioms PRChecksC.PR12.slack_values
#print axioms PRChecksC.PR12.constraints_strict
#print axioms PRChecksC.PR12.margin_values
#print axioms PRChecksC.PR12.kappa_witness
#print axioms PRChecksC.PR12.kappa_at_margin_rejected
#print axioms PRChecksC.PR12.inflated_roles_rejected
