import PRChecksB

#print axioms PRChecksB.exponent_certificate
#print axioms PRChecksB.log_le_of_pow
#print axioms PRChecksB.log_split
#print axioms PRChecksB.log_15625
#print axioms PRChecksB.log_15625_note
#print axioms PRChecksB.log_125000
#print axioms PRChecksB.neglog_bounds
#print axioms PRChecksB.log_21952
#print axioms PRChecksB.log_21952_lt_10
#print axioms PRChecksB.log_125000_gt
#print axioms PRChecksB.log_prod
#print axioms PRChecksB.certified_saving_le
#print axioms PRChecksB.ceiling_half
#print axioms PRChecksB.min_g3_g4_le
#print axioms PRChecksB.ceiling_fifth
#print axioms PRChecksB.PR5.v_eq
#print axioms PRChecksB.PR5.c22
#print axioms PRChecksB.PR5.counts
#print axioms PRChecksB.PR5.s_eq
#print axioms PRChecksB.PR5.eta
#print axioms PRChecksB.PR5.deficit_slack
#print axioms PRChecksB.PR5.log_m
#print axioms PRChecksB.PR5.log_enclosure_hi_lt
#print axioms PRChecksB.PR5.complex_exponent
#print axioms PRChecksB.PR5.gates
#print axioms PRChecksB.PR5.guard_constants
#print axioms PRChecksB.PR5.fast_gaussian_repeats
#print axioms PRChecksB.PR5.saving_ratio
#print axioms PRChecksB.PR5.bit_counts
#print axioms PRChecksB.PR5.bit_eta
#print axioms PRChecksB.PR5.bit_deficit_slack
#print axioms PRChecksB.PR5.bit_log
#print axioms PRChecksB.PR5.bit_exponent
#print axioms PRChecksB.PR5.bit_exponent_29643
#print axioms PRChecksB.PR5.Base59.parameter_origin
#print axioms PRChecksB.PR5.Base59.exponents_certified
#print axioms PRChecksB.PR5.Base59.recurrence_values
#print axioms PRChecksB.PR5.Base59.slack_values
#print axioms PRChecksB.PR5.Base59.constraint_slacks
#print axioms PRChecksB.PR5.Base59.margin_values
#print axioms PRChecksB.PR5.Base59.kappa_witness
#print axioms PRChecksB.PR5.Base59.note_lines
#print axioms PRChecksB.PR5.Base59.scoped_ceiling
#print axioms PRChecksB.PR5.Fast.parameter_origin
#print axioms PRChecksB.PR5.Fast.exponents_certified
#print axioms PRChecksB.PR5.Fast.fast_ok
#print axioms PRChecksB.PR5.Fast.recurrence_values
#print axioms PRChecksB.PR5.Fast.slack_values
#print axioms PRChecksB.PR5.Fast.constraint_slacks
#print axioms PRChecksB.PR5.Fast.margin_values
#print axioms PRChecksB.PR5.Fast.kappa_witness
#print axioms PRChecksB.PR5.Fast.note_lines
#print axioms PRChecksB.PR5.Fast.ceiling_values
#print axioms PRChecksB.PR5.Fast.scoped_ceiling
#print axioms PRChecksB.PR5.Fast.g4_exceeds_a_min
#print axioms PRChecksB.PR5.Fast.guard_forces_beta
#print axioms PRChecksB.PR5.Fast.leaf_iff
#print axioms PRChecksB.PR5.Fast.original_complex_infeasible
#print axioms PRChecksB.PR5.Fast.compressed_complex_feasible
#print axioms PRChecksB.PR5.Certified.Pw_tau_certified
#print axioms PRChecksB.PR5.Certified.fixed_tau_ceiling_beaten
#print axioms PRChecksB.PR5.Certified.certified_ceiling
#print axioms PRChecksB.PR5.Certified.certified_ceiling_attained
#print axioms PRChecksB.PR5Analytic.chirp_square
#print axioms PRChecksB.PR5Analytic.chirp_split
#print axioms PRChecksB.PR5Analytic.step_cost
#print axioms PRChecksB.PR5Analytic.step_phase
#print axioms PRChecksB.PR5Analytic.step_identity
#print axioms PRChecksB.PR5Analytic.step_nonneg
#print axioms PRChecksB.PR5Analytic.potential_bounds
#print axioms PRChecksB.PR5Analytic.path_constant
#print axioms PRChecksB.PR5Analytic.path_bound
#print axioms PRChecksB.PR5Analytic.inner_sum_bound
#print axioms PRChecksB.PR5Analytic.inner_sum_constant
#print axioms PRChecksB.PR5Analytic.kappa0_bounds
#print axioms PRChecksB.PR5Analytic.log_201
#print axioms PRChecksB.PR5Analytic.neumann_log
#print axioms PRChecksB.PR5Analytic.neumann_power
#print axioms PRChecksB.PR5Analytic.neumann_le_p
#print axioms PRChecksB.PR5Analytic.script_kappa0
#print axioms PRChecksB.PR5Analytic.script_step
#print axioms PRChecksB.PR5Analytic.sample0
#print axioms PRChecksB.PR5Analytic.sample1
#print axioms PRChecksB.PR5Analytic.sample2
#print axioms PRChecksB.PR5Analytic.gaussian_width
#print axioms PRChecksB.PR5Analytic.neumann_le_30d
#print axioms PRChecksB.PR5Analytic.theta_window
#print axioms PRChecksB.PR5Analytic.alpha_theta
#print axioms PRChecksB.PR5Analytic.exp_half_pi
#print axioms PRChecksB.PR5Analytic.lemma46_constant
#print axioms PRChecksB.PR5Analytic.lemma46_dyadic
#print axioms PRChecksB.PR5Analytic.neumann_norms
#print axioms PRChecksB.PR5Analytic.sqrt_window
#print axioms PRChecksB.PR5Analytic.gamma_S_constant
#print axioms PRChecksB.PR5Analytic.F_constant
#print axioms PRChecksB.PR5Analytic.window_E
#print axioms PRChecksB.PR5Analytic.window_E_length
#print axioms PRChecksB.PR5Analytic.gamma_E_constant
#print axioms PRChecksB.PR5Analytic.error_budgets
#print axioms PRChecksB.PR5Analytic.budget_S
#print axioms PRChecksB.PR5Analytic.budget_E
#print axioms PRChecksB.PR5Analytic.windows_lt_2p
#print axioms PRChecksB.PR6.v_eq
#print axioms PRChecksB.PR6.c49
#print axioms PRChecksB.PR6.roles
#print axioms PRChecksB.PR6.counts
#print axioms PRChecksB.PR6.eta
#print axioms PRChecksB.PR6.eta_numerators
#print axioms PRChecksB.PR6.deficit_slack
#print axioms PRChecksB.PR6.log_m
#print axioms PRChecksB.PR6.log_enclosure_hi_lt
#print axioms PRChecksB.PR6.bit_exponent
#print axioms PRChecksB.PR6.bit_exponent_325018
#print axioms PRChecksB.PR6.guard_constants
#print axioms PRChecksB.PR6.parameter_origin
#print axioms PRChecksB.PR6.exponents_certified
#print axioms PRChecksB.PR6.recurrence_values
#print axioms PRChecksB.PR6.slack_values
#print axioms PRChecksB.PR6.constraint_slacks
#print axioms PRChecksB.PR6.margin_values
#print axioms PRChecksB.PR6.kappa_witness
#print axioms PRChecksB.PR6.note_lines
#print axioms PRChecksB.PR6.ceiling_values
#print axioms PRChecksB.PR6.scoped_ceiling
#print axioms PRChecksB.PR6.g4_exceeds_a_min
#print axioms PRChecksB.PR6.window_size
#print axioms PRChecksB.PR6.Certified.Pw_tau_certified
#print axioms PRChecksB.PR6.Certified.fixed_tau_ceiling_beaten
#print axioms PRChecksB.PR6.Certified.certified_ceiling
#print axioms PRChecksB.PR6.Certified.certified_ceiling_attained
#print axioms PRChecksB.PR7.v_eq
#print axioms PRChecksB.PR7.c2_eq
#print axioms PRChecksB.PR7.bit_counts
#print axioms PRChecksB.PR7.bit_eta
#print axioms PRChecksB.PR7.bit_deficit_slack
#print axioms PRChecksB.PR7.bit_log
#print axioms PRChecksB.PR7.bit_exponent
#print axioms PRChecksB.PR7.producer_arith
#print axioms PRChecksB.PR7.vc_eq
#print axioms PRChecksB.PR7.complex_counts
#print axioms PRChecksB.PR7.complex_eta
#print axioms PRChecksB.PR7.complex_deficit_slack
#print axioms PRChecksB.PR7.complex_log
#print axioms PRChecksB.PR7.complex_exponent
#print axioms PRChecksB.PR7.complex_gates
#print axioms PRChecksB.PR7.guard_constants
#print axioms PRChecksB.PR7.parameter_origin
#print axioms PRChecksB.PR7.exponents_certified
#print axioms PRChecksB.PR7.recurrence_values
#print axioms PRChecksB.PR7.slack_values
#print axioms PRChecksB.PR7.constraint_slacks
#print axioms PRChecksB.PR7.margin_values
#print axioms PRChecksB.PR7.kappa_witness
#print axioms PRChecksB.PR7.note_lines
#print axioms PRChecksB.PR7.scoped_ceiling
#print axioms PRChecksB.PR7.motif_algebra
#print axioms PRChecksB.PR7.small_controls
