import Mathlib.Tactic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Algebra.Order.BigOperators.GroupWithZero.List
import KappaCheck.CrocSwap

/-!
# Main's selected witness `κ = 25508460085039 / 5·10¹⁷`

Generated by `formal/lean/gen_selected.py` from `research/matrix-exponent-synthesis/candidate/arithmetic.json` and `certificates/copied-centers-network.json`;
do not edit by hand.

* **A.** Moments as real-number inequalities. For each network,
  `Φ(a) = (1/W) Σ_t n_t (t/m)^(1-a) < 1` (`matrix-exponent-synthesis.tex`, eq. `moment`), with
  the bit saving `a_b` and the complex saving `a_c = 717/10⁷`. The proof bounds `log(m/t)` by
  series for `log(n/(n-1))` and `exp` by its Taylor bound. Negative controls: `Φ(a + shift) > 1`.
* **B.** The finite bridge: semantic constants, halving degrees, wire bits and the row gap,
  from their formulas in `balanced_assembly.py`.
* **C.** The 47 assembly slacks and seven margins, defined by `balanced_assembly.py`'s formulas
  over the parameters; all slacks are positive, the minimum margin is `G = εq`, and `κ < G`.
-/

namespace KappaCheck.Selected
open Real KappaCheck.CrocSwap

set_option maxRecDepth 100000

/-! ## A. Moments -/

/-- the moment `Φ(a) = (1/W) Σ_t n_t (t/m)^(1-a)` -/
noncomputable def Φ (m W : ℕ) (rows : List (ℕ × ℕ)) (a : ℝ) : ℝ :=
  (rows.map fun r => (r.2 : ℝ) * ((r.1 : ℝ) / m) ^ (1 - a)).sum / W

/-- `exp` upper bound from `Real.exp_bound'` with four terms -/
def P4 (v : ℚ) : ℚ := 1 + v + v ^ 2 / 2 + v ^ 3 / 6 + 5 * v ^ 4 / 96

/-- `exp` lower bound: its first five Taylor terms -/
def S5 (v : ℚ) : ℚ := 1 + v + v ^ 2 / 2 + v ^ 3 / 6 + v ^ 4 / 24

theorem exp_le_P4 {v : ℝ} (h0 : 0 ≤ v) (h1 : v ≤ 1) :
    exp v ≤ 1 + v + v ^ 2 / 2 + v ^ 3 / 6 + 5 * v ^ 4 / 96 := by
  have := Real.exp_bound' h0 h1 (n := 4) (by norm_num)
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial] at this
  norm_num at this
  linarith

theorem S5_le_exp {v : ℝ} (h0 : 0 ≤ v) :
    1 + v + v ^ 2 / 2 + v ^ 3 / 6 + v ^ 4 / 24 ≤ exp v := by
  have := Real.sum_le_exp_of_nonneg h0 5
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial] at this
  norm_num at this
  linarith

theorem rpow_split {m t a : ℝ} (ht : 0 < t) (hm : 0 < m) :
    (t / m) ^ (1 - a) = t / m * exp (Real.log (m / t) * a) := by
  rw [Real.rpow_sub (div_pos ht hm), Real.rpow_one, div_eq_mul_inv (t / m),
    ← Real.inv_rpow (div_pos ht hm).le, inv_div, Real.rpow_def_of_pos (div_pos hm ht)]

/-- one term from above: `(t/m)^(1-a) ≤ (t/m)·U` -/
theorem term_le {m t a H U : ℝ} (ht : 0 < t) (htm : t ≤ m) (ha : 0 ≤ a)
    (hH : Real.log (m / t) ≤ H) (h1 : a * H ≤ 1)
    (hU : 1 + a * H + (a * H) ^ 2 / 2 + (a * H) ^ 3 / 6 + 5 * (a * H) ^ 4 / 96 ≤ U) :
    (t / m) ^ (1 - a) ≤ t / m * U := by
  have hm : 0 < m := lt_of_lt_of_le ht htm
  have hlog0 : 0 ≤ Real.log (m / t) := Real.log_nonneg (by rw [le_div_iff₀ ht]; linarith)
  rw [rpow_split ht hm]
  apply mul_le_mul_of_nonneg_left _ (div_pos ht hm).le
  calc exp (Real.log (m / t) * a) ≤ exp (a * H) := by
        apply Real.exp_le_exp.mpr; nlinarith
    _ ≤ _ := (exp_le_P4 (mul_nonneg ha (hlog0.trans hH)) h1).trans hU

/-- one term from below: `(t/m)·D ≤ (t/m)^(1-a)` -/
theorem le_term {m t a H D : ℝ} (ht : 0 < t) (htm : t ≤ m) (ha : 0 ≤ a)
    (hH : H ≤ Real.log (m / t)) (hH0 : 0 ≤ H)
    (hD : D ≤ 1 + a * H + (a * H) ^ 2 / 2 + (a * H) ^ 3 / 6 + (a * H) ^ 4 / 24) :
    t / m * D ≤ (t / m) ^ (1 - a) := by
  have hm : 0 < m := lt_of_lt_of_le ht htm
  rw [rpow_split ht hm]
  apply mul_le_mul_of_nonneg_left _ (div_pos ht hm).le
  calc D ≤ _ := hD
    _ ≤ exp (a * H) := S5_le_exp (mul_nonneg ha hH0)
    _ ≤ exp (Real.log (m / t) * a) := by apply Real.exp_le_exp.mpr; nlinarith

theorem moment_lt_one {m W : ℕ} {rows : List (ℕ × ℕ)} {a : ℝ} {U : ℕ → ℝ} (hW : 0 < W)
    (h : ∀ r ∈ rows, ((r.1 : ℝ) / m) ^ (1 - a) ≤ r.1 / m * U r.1)
    (hs : (rows.map fun r => (r.2 : ℝ) * (r.1 / m * U r.1)).sum < W) : Φ m W rows a < 1 := by
  unfold Φ
  rw [div_lt_one (by exact_mod_cast hW)]
  refine lt_of_le_of_lt (List.sum_le_sum fun r hr => ?_) hs
  exact mul_le_mul_of_nonneg_left (h r hr) (Nat.cast_nonneg _)

theorem one_lt_moment {m W : ℕ} {rows : List (ℕ × ℕ)} {a : ℝ} {D : ℕ → ℝ} (hW : 0 < W)
    (h : ∀ r ∈ rows, r.1 / m * D r.1 ≤ ((r.1 : ℝ) / m) ^ (1 - a))
    (hs : (W : ℝ) < (rows.map fun r => (r.2 : ℝ) * (r.1 / m * D r.1)).sum) : 1 < Φ m W rows a := by
  unfold Φ
  rw [one_lt_div (by exact_mod_cast hW)]
  refine lt_of_lt_of_le hs (List.sum_le_sum fun r hr => ?_)
  exact mul_le_mul_of_nonneg_left (h r hr) (Nat.cast_nonneg _)

theorem log_list (rs : List (ℝ × ℤ)) (hpos : ∀ p ∈ rs, 0 < p.1) :
    Real.log (rs.map fun p => p.1 ^ p.2).prod = (rs.map fun p => (p.2 : ℝ) * Real.log p.1).sum := by
  induction rs with
  | nil => simp
  | cons p rs ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    have h1 : 0 < p.1 := hpos p (by simp)
    have h2 : 0 < (rs.map fun p => p.1 ^ p.2).prod := by
      apply List.prod_pos
      intro x hx
      simp only [List.mem_map] at hx
      obtain ⟨q, hq, rfl⟩ := hx
      exact zpow_pos (hpos q (by simp [hq])) _
    rw [Real.log_mul (zpow_pos h1 _).ne' h2.ne', Real.log_zpow,
      ih (fun q hq => hpos q (by simp [hq]))]


/-! ### Basis logarithms `log(n/(n-1)) = -log(1 - 1/n)`, by `neglog_bounds` -/

theorem log_16_15 : (645385211375711716729239156839929281289 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (16 / 15) ∧
    Real.log (16 / 15) ≤ (64538521137571171672923915683992928129 / 1000000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (16 / 15) = -Real.log (1 - 1 / 16) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 16) (by norm_num) (by norm_num) 36
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_25_24 : (102054986300637823886442662888299675443 / 2500000000000000000000000000000000000000 : ℝ) ≤ Real.log (25 / 24) ∧
    Real.log (25 / 24) ≤ (408219945202551295545770651553198701773 / 10000000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (25 / 24) = -Real.log (1 - 1 / 25) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 25) (by norm_num) (by norm_num) 31
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_81_80 : (124225199985571533112931286312089067623 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (81 / 80) ∧
    Real.log (81 / 80) ≤ (15528149998196441639116410789011133453 / 1250000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (81 / 80) = -Real.log (1 - 1 / 81) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 81) (by norm_num) (by norm_num) 23
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_126_125 : (79681696491768735107973390678447884307 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (126 / 125) ∧
    Real.log (126 / 125) ≤ (19920424122942183776993347669611971077 / 2500000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (126 / 125) = -Real.log (1 - 1 / 126) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 126) (by norm_num) (by norm_num) 20
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_176_175 : (28490105573188637120003269511402817177 / 5000000000000000000000000000000000000000 : ℝ) ≤ Real.log (176 / 175) ∧
    Real.log (176 / 175) ≤ (11396042229275454848001307804561126871 / 2000000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (176 / 175) = -Real.log (1 - 1 / 176) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 176) (by norm_num) (by norm_num) 19
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_351_350 : (28530689824064465151196209791641419839 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (351 / 350) ∧
    Real.log (351 / 350) ≤ (89158405700201453597488155598879437 / 31250000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (351 / 350) = -Real.log (1 - 1 / 351) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 351) (by norm_num) (by norm_num) 17
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_715_714 : (6997901772116342744128165298135031021 / 5000000000000000000000000000000000000000 : ℝ) ≤ Real.log (715 / 714) ∧
    Real.log (715 / 714) ≤ (13995803544232685488256330596270062043 / 10000000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (715 / 714) = -Real.log (1 - 1 / 715) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 715) (by norm_num) (by norm_num) 15
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_343_342 : (29197101033347630993082031384576743033 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (343 / 342) ∧
    Real.log (343 / 342) ≤ (14598550516673815496541015692288371517 / 5000000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (343 / 342) = -Real.log (1 - 1 / 343) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 343) (by norm_num) (by norm_num) 17
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_576_575 : (17376198985407992856117043315394202543 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (576 / 575) ∧
    Real.log (576 / 575) ≤ (1086012436587999553507315207212137659 / 625000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (576 / 575) = -Real.log (1 - 1 / 576) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 576) (by norm_num) (by norm_num) 15
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

theorem log_481_480 : (20811662038245673394179351571695841547 / 10000000000000000000000000000000000000000 : ℝ) ≤ Real.log (481 / 480) ∧
    Real.log (481 / 480) ≤ (5202915509561418348544837892923960387 / 2500000000000000000000000000000000000000 : ℝ) := by
  have e : Real.log (481 / 480) = -Real.log (1 - 1 / 481) := by
    rw [← Real.log_inv]; norm_num
  have h := neglog_bounds (1 / 481) (by norm_num) (by norm_num) 16
  rw [e]; unfold ps at h
  simp only [Finset.sum_range_succ, Finset.sum_range_zero] at h
  constructor
  · refine le_trans ?_ h.1; norm_num
  · refine h.2.trans ?_; norm_num

/-! ### Parameters of the two moments -/

/-- the bit saving `a_b` -/
def aB : ℚ := 102039046058023 / 2000000000000000000

/-- the complex saving `a_c` -/
def aC : ℚ := 717 / 10000000

/-! ### Bit network (`m = 575`) -/

/-- bit network: `(t, n_t)` for every child width `t` -/
def bitRows : List (ℕ × ℕ) := [
  (1, 1725399142), (2, 83474797), (3, 45979944), (4, 25771845),
  (5, 20048226), (6, 18832860), (7, 17285926), (8, 13320151),
  (9, 10863958), (10, 8899436), (11, 8550388), (12, 6150660),
  (13, 5359966), (14, 3947398), (15, 3264367), (16, 2045758),
  (17, 9608825), (18, 928096), (19, 299299), (20, 282371),
  (21, 16346100), (22, 97405), (23, 72402275), (25, 64793806),
  (481, 8146600), (525, 64793806), (529, 64211400)]
/-- bit network: lower bounds on `log(m/t)` -/
def bitHlo : ℕ → ℚ
  | 1 => 15885925101993376100020678745656428493727 / 2500000000000000000000000000000000000000
  | 2 => 14153057150593512826477598442010987073539 / 2500000000000000000000000000000000000000
  | 3 => 26278788760646203743065131306700228464219 / 5000000000000000000000000000000000000000
  | 4 => 12420189199193649552934518138365545653351 / 2500000000000000000000000000000000000000
  | 5 => 47449321283632500654075121650363837579659 / 10000000000000000000000000000000000000000
  | 6 => 22813052857846477195978970699409345623843 / 5000000000000000000000000000000000000000
  | 7 => 8816919783484074269805837509638783335709 / 2000000000000000000000000000000000000000
  | 8 => 10687321247793786279391437834720104233163 / 2500000000000000000000000000000000000000
  | 9 => 2598215914663206910761113140260949992623 / 625000000000000000000000000000000000000
  | 10 => 40517849478033047559902800435782071898907 / 10000000000000000000000000000000000000000
  | 11 => 395647476799897989594632792029744209767 / 100000000000000000000000000000000000000
  | 12 => 19347316955046750648892810092118462783467 / 5000000000000000000000000000000000000000
  | 13 => 7578841366671627407909568113394505585373 / 2000000000000000000000000000000000000000
  | 14 => 37153127111820918254856866333612150997793 / 10000000000000000000000000000000000000000
  | 15 => 36463198396951403740122669281138580533189 / 10000000000000000000000000000000000000000
  | 16 => 358178131855756920233934301242986512519 / 100000000000000000000000000000000000000
  | 17 => 7042313393482268719517473760778889723807 / 2000000000000000000000000000000000000000
  | 18 => 270624865851655136546917883043698704697 / 78125000000000000000000000000000000000
  | 19 => 2131206913519318737499527541484198662659 / 625000000000000000000000000000000000000
  | 20 => 6717275534486718893146095844240061243631 / 2000000000000000000000000000000000000000
  | 21 => 1323939041229570977403069407158746385283 / 400000000000000000000000000000000000000
  | 22 => 8158318968597586466322739497098163823987 / 2500000000000000000000000000000000000000
  | 23 => 16094379124341003746007593332261876395249 / 5000000000000000000000000000000000000000
  | 25 => 3135494215929149690806752831810196118441 / 1000000000000000000000000000000000000000
  | 481 => 1785027706915892595866883856658056287881 / 10000000000000000000000000000000000000000
  | 525 => 113714722757158367882693564305613355197 / 1250000000000000000000000000000000000000
  | 529 => 833816089390510583947658346421791606087 / 10000000000000000000000000000000000000000
  | _ => 0
/-- bit network: upper bounds on `log(m/t)` -/
def bitHhi : ℕ → ℚ
  | 1 => 63543700407973504400082714982625713975047 / 10000000000000000000000000000000000000000
  | 2 => 1415305715059351282647759844201098707357 / 250000000000000000000000000000000000000
  | 3 => 52557577521292407486130262613400456928553 / 10000000000000000000000000000000000000000
  | 4 => 49680756796774598211738072553462182613513 / 10000000000000000000000000000000000000000
  | 5 => 47449321283632500654075121650363837579763 / 10000000000000000000000000000000000000000
  | 6 => 22813052857846477195978970699409345623893 / 5000000000000000000000000000000000000000
  | 7 => 44084598917420371349029187548193916678643 / 10000000000000000000000000000000000000000
  | 8 => 21374642495587572558782875669440208466373 / 5000000000000000000000000000000000000000
  | 9 => 41571454634611310572177810244175199882059 / 10000000000000000000000000000000000000000
  | 10 => 10129462369508261889975700108945517974749 / 2500000000000000000000000000000000000000
  | 11 => 39564747679989798959463279202974420976789 / 10000000000000000000000000000000000000000
  | 12 => 38694633910093501297785620184236925567019 / 10000000000000000000000000000000000000000
  | 13 => 37894206833358137039547840566972527926951 / 10000000000000000000000000000000000000000
  | 14 => 9288281777955229563714216583403037749469 / 2500000000000000000000000000000000000000
  | 15 => 36463198396951403740122669281138580533269 / 10000000000000000000000000000000000000000
  | 16 => 35817813185575692023393430124298651251979 / 10000000000000000000000000000000000000000
  | 17 => 35211566967411343597587368803894448619117 / 10000000000000000000000000000000000000000
  | 18 => 8659995707252964369501372257398358550323 / 2500000000000000000000000000000000000000
  | 19 => 266400864189914842187440942685524832833 / 78125000000000000000000000000000000000
  | 20 => 33586377672433594465730479221200306218229 / 10000000000000000000000000000000000000000
  | 21 => 33098476030739274435076735178968659632149 / 10000000000000000000000000000000000000000
  | 22 => 16316637937195172932645478994196327648011 / 5000000000000000000000000000000000000000
  | 23 => 4023594781085250936501898333065469098821 / 1250000000000000000000000000000000000000
  | 25 => 31354942159291496908067528318101961184479 / 10000000000000000000000000000000000000000
  | 481 => 1785027706915892595866883856658056287887 / 10000000000000000000000000000000000000000
  | 525 => 454858891028633471530774257222453420791 / 5000000000000000000000000000000000000000
  | 529 => 83381608939051058394765834642179160609 / 1000000000000000000000000000000000000000
  | _ => 0
/-- bit network: upward-rounded `P₄(a·Hhi t)` -/
def bitU : ℕ → ℚ
  | 1 => 5001621247430676050916344072633644509633 / 5000000000000000000000000000000000000000
  | 2 => 10002888746063257636752160437347471381699 / 10000000000000000000000000000000000000000
  | 3 => 156291903470014063299216610637906621339 / 156250000000000000000000000000000000000
  | 4 => 5001267504887464116404546110279587096231 / 5000000000000000000000000000000000000000
  | 5 => 1250302641848415625564005304613741481643 / 1250000000000000000000000000000000000000
  | 6 => 5001164046555054503529042880043054002143 / 5000000000000000000000000000000000000000
  | 7 => 10002249428168113096775435570311406319903 / 10000000000000000000000000000000000000000
  | 8 => 2500545321498980368013172441319486481687 / 2500000000000000000000000000000000000000
  | 9 => 156283143448838364866556461191935937997 / 156250000000000000000000000000000000000
  | 10 => 10002067415035326514854743635592973924779 / 10000000000000000000000000000000000000000
  | 11 => 2000403755660253440703067600559911612977 / 2000000000000000000000000000000000000000
  | 12 => 1250246797081047727163145705299492542239 / 1250000000000000000000000000000000000000
  | 13 => 5000966765630632947033355027670304992917 / 5000000000000000000000000000000000000000
  | 14 => 5000947857244123386962513649911959700689 / 5000000000000000000000000000000000000000
  | 15 => 1000186050804336966820137754237302167009 / 1000000000000000000000000000000000000000
  | 16 => 10001827574725794956082639758556654104587 / 10000000000000000000000000000000000000000
  | 17 => 2500449159681997196010013656191506772611 / 2500000000000000000000000000000000000000
  | 18 => 2000353494316211271248029652958455522247 / 2000000000000000000000000000000000000000
  | 19 => 10001739881905160274889865503971768459487 / 10000000000000000000000000000000000000000
  | 20 => 10001713707792065853669611053954553215829 / 10000000000000000000000000000000000000000
  | 21 => 10001688811048159995353368250122675133027 / 10000000000000000000000000000000000000000
  | 22 => 5000832536388983737529814296839251126589 / 5000000000000000000000000000000000000000
  | 23 => 5000821194975107859056107615668807560929 / 5000000000000000000000000000000000000000
  | 25 => 1250199980269333462691891798615145640079 / 1250000000000000000000000000000000000000
  | 481 => 10000091071676900417819724748330529324577 / 10000000000000000000000000000000000000000
  | 525 => 2000009282695008354397615538016786384651 / 2000000000000000000000000000000000000000
  | 529 => 10000042540989661152908058927663987776913 / 10000000000000000000000000000000000000000
  | _ => 0
/-- bit network: downward-rounded `S₅((a+shift)·Hlo t)` (negative control) -/
def bitD : ℕ → ℚ
  | 1 => 10003242494861357307557199417765320384553 / 10000000000000000000000000000000000000000
  | 2 => 1000288874606326257464822482455292319897 / 1000000000000000000000000000000000000000
  | 3 => 2500670455520226192444980894498635015109 / 2500000000000000000000000000000000000000
  | 4 => 5001267504887466386092536958191251015121 / 5000000000000000000000000000000000000000
  | 5 => 5001210567393664696415428604167032831663 / 5000000000000000000000000000000000000000
  | 6 => 250058202327752831621679117750100212913 / 250000000000000000000000000000000000000
  | 7 => 10002249428168117239650443281305907613193 / 10000000000000000000000000000000000000000
  | 8 => 5001090642997962756098646011710050756559 / 5000000000000000000000000000000000000000
  | 9 => 10002121180725659298694346738102379868381 / 10000000000000000000000000000000000000000
  | 10 => 2500516853758832594313934296496940568831 / 2500000000000000000000000000000000000000
  | 11 => 78140771705478679592530129714939192347 / 78125000000000000000000000000000000000
  | 12 => 10001974376648385529306730073494601508589 / 10000000000000000000000000000000000000000
  | 13 => 500096676563063476934285008265426897701 / 500000000000000000000000000000000000000
  | 14 => 2000379142897650071092526523651230411019 / 2000000000000000000000000000000000000000
  | 15 => 10001860508043373190434441438334292328457 / 10000000000000000000000000000000000000000
  | 16 => 5000913787362899211177404404648122129361 / 5000000000000000000000000000000000000000
  | 17 => 10001796638727992197332869976012494491971 / 10000000000000000000000000000000000000000
  | 18 => 5000883735790529859614659976835093413403 / 5000000000000000000000000000000000000000
  | 19 => 2000347976381032717998081553574879574123 / 2000000000000000000000000000000000000000
  | 20 => 1000171370779206912307247169779663956099 / 1000000000000000000000000000000000000000
  | 21 => 2000337762209632644211094197044939975461 / 2000000000000000000000000000000000000000
  | 22 => 10001665072777970658888749430747932652159 / 10000000000000000000000000000000000000000
  | 23 => 10001642389950218861747760724496565090431 / 10000000000000000000000000000000000000000
  | 25 => 400063993686186830772523111855461510123 / 400000000000000000000000000000000000000
  | 481 => 10000091071676900596323404531898503845377 / 10000000000000000000000000000000000000000
  | 525 => 10000046413475041862960229788065998791159 / 10000000000000000000000000000000000000000
  | 529 => 1250005317623707654536248558067723595727 / 1250000000000000000000000000000000000000
  | _ => 0

set_option maxHeartbeats 20000000 in
/-- bit network: `Hlo t ≤ log(m/t) ≤ Hhi t` for every row -/
theorem bit_logs : ∀ r ∈ bitRows, (bitHlo r.1 : ℝ) ≤ Real.log (((575 : ℕ) : ℝ) / (r.1 : ℝ)) ∧
    Real.log (((575 : ℕ) : ℝ) / (r.1 : ℝ)) ≤ bitHhi r.1 := by
  intro r hr
  simp only [bitRows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((1 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (64 : ℤ)), ((25 : ℝ) / 24, (46 : ℤ)), ((81 : ℝ) / 80, (28 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((2 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (57 : ℤ)), ((25 : ℝ) / 24, (41 : ℤ)), ((81 : ℝ) / 80, (25 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((3 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (53 : ℤ)), ((25 : ℝ) / 24, (38 : ℤ)), ((81 : ℝ) / 80, (23 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((4 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (50 : ℤ)), ((25 : ℝ) / 24, (36 : ℤ)), ((81 : ℝ) / 80, (22 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((5 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (48 : ℤ)), ((25 : ℝ) / 24, (34 : ℤ)), ((81 : ℝ) / 80, (21 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((6 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (46 : ℤ)), ((25 : ℝ) / 24, (33 : ℤ)), ((81 : ℝ) / 80, (20 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((7 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (45 : ℤ)), ((25 : ℝ) / 24, (31 : ℤ)), ((81 : ℝ) / 80, (20 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((8 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (43 : ℤ)), ((25 : ℝ) / 24, (31 : ℤ)), ((81 : ℝ) / 80, (19 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((9 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (42 : ℤ)), ((25 : ℝ) / 24, (30 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((10 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (41 : ℤ)), ((25 : ℝ) / 24, (29 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((11 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (41 : ℤ)), ((25 : ℝ) / 24, (27 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((12 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (39 : ℤ)), ((25 : ℝ) / 24, (28 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((13 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (39 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((351 : ℝ) / 350, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_351_350).1, (log_351_350).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((14 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (38 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((15 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (37 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (16 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((16 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (36 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (16 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((17 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (37 : ℤ)), ((25 : ℝ) / 24, (23 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ)), ((351 : ℝ) / 350, (-1 : ℤ)), ((715 : ℝ) / 714, (1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2, (log_351_350).1, (log_351_350).2, (log_715_714).1, (log_715_714).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((18 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (35 : ℤ)), ((25 : ℝ) / 24, (25 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((19 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (36 : ℤ)), ((25 : ℝ) / 24, (22 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (-3 : ℤ)), ((343 : ℝ) / 342, (1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_343_342).1, (log_343_342).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((20 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (24 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((21 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (23 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((22 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (22 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((23 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (32 : ℤ)), ((25 : ℝ) / 24, (24 : ℤ)), ((81 : ℝ) / 80, (14 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((25 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (32 : ℤ)), ((25 : ℝ) / 24, (22 : ℤ)), ((81 : ℝ) / 80, (14 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((481 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (2 : ℤ)), ((25 : ℝ) / 24, (1 : ℤ)), ((81 : ℝ) / 80, (1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ)), ((481 : ℝ) / 480, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_576_575).1, (log_576_575).2, (log_481_480).1, (log_481_480).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((525 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (2 : ℤ)), ((25 : ℝ) / 24, (-1 : ℤ)), ((81 : ℝ) / 80, (1 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((576 : ℝ) / 575, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((575 : ℕ) : ℝ) / ((529 : ℕ) : ℝ) = ([((25 : ℝ) / 24, (2 : ℤ)), ((576 : ℝ) / 575, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, bitHlo, bitHhi]
    push_cast
    constructor <;> linarith [(log_25_24).1, (log_25_24).2, (log_576_575).1, (log_576_575).2]

set_option maxHeartbeats 20000000 in
/-- bit network: the rational side conditions of `term_le` and `le_term` -/
theorem bit_hints : ∀ r ∈ bitRows, 0 < r.1 ∧ r.1 < 575 ∧ 0 ≤ bitHlo r.1 ∧
    aB * bitHhi r.1 ≤ 1 ∧ P4 (aB * bitHhi r.1) ≤ bitU r.1 ∧
    bitD r.1 ≤ S5 ((aB + 1 / 10000000000000000) * bitHlo r.1) := by
  intro r hr
  simp only [bitRows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> norm_num [bitHlo, bitHhi, bitU, bitD, aB, P4, S5]

/-- bit network: `Φ(a) < 1`, the source's moment test -/
theorem bit_moment : Φ 575 137151806 bitRows (aB : ℝ) < 1 := by
  apply moment_lt_one (U := fun t => (bitU t : ℝ)) (by norm_num)
  · intro r hr
    obtain ⟨h0, hm, -, h1, h2, -⟩ := bit_hints r hr
    exact term_le (by exact_mod_cast h0) (by exact_mod_cast hm.le) (by norm_num [aB])
      (bit_logs r hr).2 (by exact_mod_cast h1) (by unfold P4 at h2; exact_mod_cast h2)
  · simp only [bitRows, bitU, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num

/-- negative control: `Φ(a + 1 / 10000000000000000) > 1`, so the moment test is tight -/
theorem bit_moment_tight : 1 < Φ 575 137151806 bitRows ((aB : ℝ) + 1 / 10000000000000000) := by
  rw [show (aB : ℝ) + 1 / 10000000000000000 = ((aB + 1 / 10000000000000000 : ℚ) : ℝ) by push_cast; ring]
  apply one_lt_moment (D := fun t => (bitD t : ℝ)) (by norm_num)
  · intro r hr
    obtain ⟨h0, hm, hl, -, -, h3⟩ := bit_hints r hr
    exact le_term (by exact_mod_cast h0) (by exact_mod_cast hm.le) (by norm_num [aB])
      (bit_logs r hr).1 (by exact_mod_cast hl) (by unfold S5 at h3; exact_mod_cast h3)
  · simp only [bitRows, bitD, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num

/-! ### Complex network (`m = 784`) -/

/-- complex network: `(t, n_t)` for every child width `t` -/
def cxRows : List (ℕ × ℕ) := [
  (1, 540572760), (2, 336785904), (3, 161899920), (4, 117097344),
  (5, 93051504), (6, 64779624), (7, 52822224), (8, 70243992),
  (9, 32150664), (10, 50699376), (11, 22728888), (12, 47580624),
  (13, 26208000), (14, 44907408), (15, 24714144), (16, 49192416),
  (17, 20815704), (18, 52501176), (19, 22624056), (20, 46348848),
  (21, 37759176), (22, 58961448), (23, 40773096), (24, 38781288),
  (25, 2208024), (26, 3741192), (27, 43112160), (729, 21464352),
  (756, 516232080)]
/-- complex network: lower bounds on `log(m/t)` -/
def cxHlo : ℕ → ℚ
  | 1 => 16661022550876019619699084931797664328933 / 2500000000000000000000000000000000000000
  | 2 => 2985630919895231269231200925630444581749 / 500000000000000000000000000000000000000
  | 3 => 27828983658411490782421943678982700134631 / 5000000000000000000000000000000000000000
  | 4 => 13195286648076293072612924324506781488557 / 2500000000000000000000000000000000000000
  | 5 => 50549711079163074732788746394928780920483 / 10000000000000000000000000000000000000000
  | 6 => 4872649551122352847067156614338363458851 / 1000000000000000000000000000000000000000
  | 7 => 4718498871295094542774281229275886001937 / 1000000000000000000000000000000000000000
  | 8 => 11462418696676429799069844020861340068369 / 2500000000000000000000000000000000000000
  | 9 => 5583980553767735581361429373592517902849 / 1250000000000000000000000000000000000000
  | 10 => 43618239273563621638616425180347015239731 / 10000000000000000000000000000000000000000
  | 11 => 1706605499020814921527076157901574572701 / 400000000000000000000000000000000000000
  | 12 => 20897511852812037688249622464400934453879 / 5000000000000000000000000000000000000000
  | 13 => 4099459662888871111826146531153747126769 / 1000000000000000000000000000000000000000
  | 14 => 20126758453675746166785245539088547169309 / 5000000000000000000000000000000000000000
  | 15 => 39563588192481977818836294025703523874013 / 10000000000000000000000000000000000000000
  | 16 => 9729550745276566525526763717215898648181 / 2500000000000000000000000000000000000000
  | 17 => 1915597838147095883815049677422969597993 / 500000000000000000000000000000000000000
  | 18 => 943509315613560788917977844353959438551 / 250000000000000000000000000000000000000
  | 19 => 3719970041183967387870606540831212194337 / 1000000000000000000000000000000000000000
  | 20 => 36686767467964168544444103965765249558979 / 10000000000000000000000000000000000000000
  | 21 => 361988658262698485137903599235336029729 / 100000000000000000000000000000000000000
  | 22 => 35733665669920919944004582732957598636773 / 10000000000000000000000000000000000000000
  | 23 => 35289148044212581570728811409088696131321 / 10000000000000000000000000000000000000000
  | 24 => 17431775950012311141163461857110051613503 / 5000000000000000000000000000000000000000
  | 25 => 17227665977411035493390576531333452262617 / 5000000000000000000000000000000000000000
  | 26 => 17031562411644629012044572048477852793469 / 5000000000000000000000000000000000000000
  | 27 => 16842860771730393868469491309757443088161 / 5000000000000000000000000000000000000000
  | 729 => 72735288341749699508162551183911503691 / 1000000000000000000000000000000000000000
  | 756 => 72735288341749699508162551183911503691 / 2000000000000000000000000000000000000000
  | _ => 0
/-- complex network: upper bounds on `log(m/t)` -/
def cxHhi : ℕ → ℚ
  | 1 => 33322045101752039239398169863595328657939 / 5000000000000000000000000000000000000000
  | 2 => 59712618397904625384624018512608891635111 / 10000000000000000000000000000000000000000
  | 3 => 6957245914602872695605485919745675033673 / 1250000000000000000000000000000000000000
  | 4 => 6597643324038146536306462162253390744293 / 1250000000000000000000000000000000000000
  | 5 => 25274855539581537366394373197464390460297 / 5000000000000000000000000000000000000000
  | 6 => 48726495511223528470671566143383634588617 / 10000000000000000000000000000000000000000
  | 7 => 47184988712950945427742812292758860019473 / 10000000000000000000000000000000000000000
  | 8 => 45849674786705719196279376083445360273577 / 10000000000000000000000000000000000000000
  | 9 => 4467184443014188465089143498874014322289 / 1000000000000000000000000000000000000000
  | 10 => 43618239273563621638616425180347015239827 / 10000000000000000000000000000000000000000
  | 11 => 42665137475520373038176903947539364317619 / 10000000000000000000000000000000000000000
  | 12 => 835900474112481507529984898576037378157 / 200000000000000000000000000000000000000
  | 13 => 40994596628888711118261465311537471267781 / 10000000000000000000000000000000000000000
  | 14 => 20126758453675746166785245539088547169353 / 5000000000000000000000000000000000000000
  | 15 => 395635881924819778188362940257035238741 / 100000000000000000000000000000000000000
  | 16 => 3891820298110626610210705486886359459281 / 1000000000000000000000000000000000000000
  | 17 => 38311956762941917676300993548459391959947 / 10000000000000000000000000000000000000000
  | 18 => 37740372624542431556719113774158377542123 / 10000000000000000000000000000000000000000
  | 19 => 37199700411839673878706065408312121943453 / 10000000000000000000000000000000000000000
  | 20 => 1834338373398208427222205198288262477953 / 500000000000000000000000000000000000000
  | 21 => 36198865826269848513790359923533602972979 / 10000000000000000000000000000000000000000
  | 22 => 8933416417480229986001145683239399659213 / 2500000000000000000000000000000000000000
  | 23 => 176445740221062907853644057045443480657 / 50000000000000000000000000000000000000
  | 24 => 34863551900024622282326923714220103227083 / 10000000000000000000000000000000000000000
  | 25 => 3445533195482207098678115306266690452531 / 1000000000000000000000000000000000000000
  | 26 => 17031562411644629012044572048477852793507 / 5000000000000000000000000000000000000000
  | 27 => 8421430385865196934234745654878721544099 / 2500000000000000000000000000000000000000
  | 729 => 181838220854374248770406377959778759229 / 2500000000000000000000000000000000000000
  | 756 => 181838220854374248770406377959778759229 / 5000000000000000000000000000000000000000
  | _ => 0
/-- complex network: upward-rounded `P₄(a·Hhi t)` -/
def cxU : ℕ → ℚ
  | 1 => 10004779523095836041087539001597199360837 / 10000000000000000000000000000000000000000
  | 2 => 400171292455479676641058546181554819091 / 400000000000000000000000000000000000000
  | 3 => 625249467039837573608454987213630389921 / 625000000000000000000000000000000000000
  | 4 => 10003785124388286431265594192035955965443 / 10000000000000000000000000000000000000000
  | 5 => 1000362507118268301853951255187781127817 / 1000000000000000000000000000000000000000
  | 6 => 10003494300092630842831939014097037333399 / 10000000000000000000000000000000000000000
  | 7 => 10003383736045091654737346092131061959639 / 10000000000000000000000000000000000000000
  | 8 => 625205497631155714567752899216526300919 / 625000000000000000000000000000000000000
  | 9 => 10003203484251652277389875202984082540411 / 10000000000000000000000000000000000000000
  | 10 => 10003127916847119182497568723289523418499 / 10000000000000000000000000000000000000000
  | 11 => 1000305955830640176975445825168442196417 / 1000000000000000000000000000000000000000
  | 12 => 5001498576128026302993695328984558121459 / 5000000000000000000000000000000000000000
  | 13 => 1000293974459854079122282732530673143151 / 1000000000000000000000000000000000000000
  | 14 => 10002886593703261161876149181498478609883 / 10000000000000000000000000000000000000000
  | 15 => 1000283711165742403892846084550439492133 / 1000000000000000000000000000000000000000
  | 16 => 10002790824516378844019474887376098767739 / 10000000000000000000000000000000000000000
  | 17 => 10002747344625920148676544902319247493521 / 10000000000000000000000000000000000000000
  | 18 => 10002706350867870592216058375506428844609 / 10000000000000000000000000000000000000000
  | 19 => 1250333446781735956276052971603181672423 / 1250000000000000000000000000000000000000
  | 20 => 1250328848402355302395160880458593582809 / 1250000000000000000000000000000000000000
  | 21 => 1250324474441146741137727562137584387357 / 1250000000000000000000000000000000000000
  | 22 => 5001281216037684002565765075625300143929 / 5000000000000000000000000000000000000000
  | 23 => 10002530552045447187521538035390894641553 / 10000000000000000000000000000000000000000
  | 24 => 78144531477550300268341210735786035411 / 78125000000000000000000000000000000000
  | 25 => 5001235376240892545971503595867362046169 / 5000000000000000000000000000000000000000
  | 26 => 5001221312160969495690374688091366261581 / 5000000000000000000000000000000000000000
  | 27 => 2000483111586739919393878617229672323377 / 2000000000000000000000000000000000000000
  | 729 => 10000052151337728663083500865833378071667 / 10000000000000000000000000000000000000000
  | 756 => 10000026075634867394854831808237942597089 / 10000000000000000000000000000000000000000
  | _ => 0
/-- complex network: downward-rounded `S₅((a+shift)·Hlo t)` (negative control) -/
def cxD : ℕ → ℚ
  | 1 => 10004786190692342423381745912774084688139 / 10000000000000000000000000000000000000000
  | 2 => 10004288285207692025791225326482467596799 / 10000000000000000000000000000000000000000
  | 3 => 10003997040657252277312055316340801947009 / 10000000000000000000000000000000000000000
  | 4 => 2500947601125542257368644575045391642033 / 2500000000000000000000000000000000000000
  | 5 => 625226882999220640410572925575100260939 / 625000000000000000000000000000000000000
  | 6 => 312609349201438060679784651364968631137 / 312500000000000000000000000000000000000
  | 7 => 2500847114035422661142291701785846749611 / 2500000000000000000000000000000000000000
  | 8 => 10003292548574540258410520163077156447607 / 10000000000000000000000000000000000000000
  | 9 => 5001603976434073901559744303340586271759 / 5000000000000000000000000000000000000000
  | 10 => 1250391535004542421262345063893711617521 / 1250000000000000000000000000000000000000
  | 11 => 2500765956531605900679603053703973839043 / 2500000000000000000000000000000000000000
  | 12 => 10003001333011956498156663272914608784253 / 10000000000000000000000000000000000000000
  | 13 => 500147192263208993413740683078043567973 / 500000000000000000000000000000000000000
  | 14 => 5001445310108858532696423117047918585773 / 5000000000000000000000000000000000000000
  | 15 => 5001420534569744323110732676904213116939 / 5000000000000000000000000000000000000000
  | 16 => 5001397358711786298962827483629305478463 / 5000000000000000000000000000000000000000
  | 17 => 2500687794218722859924049743356111557241 / 2500000000000000000000000000000000000000
  | 18 => 10002710125927231750701269821110993811657 / 10000000000000000000000000000000000000000
  | 19 => 2500667823804237507803068209490747756471 / 2500000000000000000000000000000000000000
  | 20 => 1250329307107676580375468075814364691293 / 1250000000000000000000000000000000000000
  | 21 => 1250324927044507496651234289328024788199 / 1250000000000000000000000000000000000000
  | 22 => 400102640254328962811744210870233857307 / 400000000000000000000000000000000000000
  | 23 => 10002534081853884259115425656055108503201 / 10000000000000000000000000000000000000000
  | 24 => 10002503516353834867735537057438219811601 / 10000000000000000000000000000000000000000
  | 25 => 10002474198866879887209412400141672255063 / 10000000000000000000000000000000000000000
  | 26 => 625152876966689713214395801587032838941 / 625000000000000000000000000000000000000
  | 27 => 2000483785464023841773739361087032522229 / 2000000000000000000000000000000000000000
  | 729 => 2500013056018349148403580552928804414449 / 2500000000000000000000000000000000000000
  | 756 => 5000013056001303231400582549962313059101 / 5000000000000000000000000000000000000000
  | _ => 0

set_option maxHeartbeats 20000000 in
/-- complex network: `Hlo t ≤ log(m/t) ≤ Hhi t` for every row -/
theorem cx_logs : ∀ r ∈ cxRows, (cxHlo r.1 : ℝ) ≤ Real.log (((784 : ℕ) : ℝ) / (r.1 : ℝ)) ∧
    Real.log (((784 : ℕ) : ℝ) / (r.1 : ℝ)) ≤ cxHhi r.1 := by
  intro r hr
  simp only [cxRows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((1 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (66 : ℤ)), ((25 : ℝ) / 24, (50 : ℤ)), ((81 : ℝ) / 80, (28 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((2 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (59 : ℤ)), ((25 : ℝ) / 24, (45 : ℤ)), ((81 : ℝ) / 80, (25 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((3 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (55 : ℤ)), ((25 : ℝ) / 24, (42 : ℤ)), ((81 : ℝ) / 80, (23 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((4 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (52 : ℤ)), ((25 : ℝ) / 24, (40 : ℤ)), ((81 : ℝ) / 80, (22 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((5 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (50 : ℤ)), ((25 : ℝ) / 24, (38 : ℤ)), ((81 : ℝ) / 80, (21 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((6 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (48 : ℤ)), ((25 : ℝ) / 24, (37 : ℤ)), ((81 : ℝ) / 80, (20 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((7 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (47 : ℤ)), ((25 : ℝ) / 24, (35 : ℤ)), ((81 : ℝ) / 80, (20 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((8 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (45 : ℤ)), ((25 : ℝ) / 24, (35 : ℤ)), ((81 : ℝ) / 80, (19 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((9 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (44 : ℤ)), ((25 : ℝ) / 24, (34 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((10 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (43 : ℤ)), ((25 : ℝ) / 24, (33 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((11 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (43 : ℤ)), ((25 : ℝ) / 24, (31 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((12 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (41 : ℤ)), ((25 : ℝ) / 24, (32 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((13 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (41 : ℤ)), ((25 : ℝ) / 24, (30 : ℤ)), ((81 : ℝ) / 80, (18 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ)), ((351 : ℝ) / 350, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_351_350).1, (log_351_350).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((14 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (40 : ℤ)), ((25 : ℝ) / 24, (30 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((15 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (39 : ℤ)), ((25 : ℝ) / 24, (30 : ℤ)), ((81 : ℝ) / 80, (16 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((16 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (38 : ℤ)), ((25 : ℝ) / 24, (30 : ℤ)), ((81 : ℝ) / 80, (16 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((17 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (39 : ℤ)), ((25 : ℝ) / 24, (27 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ)), ((351 : ℝ) / 350, (-1 : ℤ)), ((715 : ℝ) / 714, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2, (log_351_350).1, (log_351_350).2, (log_715_714).1, (log_715_714).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((18 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (37 : ℤ)), ((25 : ℝ) / 24, (29 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((19 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (38 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (17 : ℤ)), ((126 : ℝ) / 125, (-1 : ℤ)), ((343 : ℝ) / 342, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_343_342).1, (log_343_342).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((20 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (36 : ℤ)), ((25 : ℝ) / 24, (28 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((21 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (36 : ℤ)), ((25 : ℝ) / 24, (27 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((22 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (36 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ)), ((176 : ℝ) / 175, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_176_175).1, (log_176_175).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((23 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (28 : ℤ)), ((81 : ℝ) / 80, (14 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ)), ((576 : ℝ) / 575, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_576_575).1, (log_576_575).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((24 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (27 : ℤ)), ((81 : ℝ) / 80, (14 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((25 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (14 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((26 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (34 : ℤ)), ((25 : ℝ) / 24, (25 : ℤ)), ((81 : ℝ) / 80, (15 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ)), ((351 : ℝ) / 350, (-1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2, (log_351_350).1, (log_351_350).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((27 : ℕ) : ℝ) = ([((16 : ℝ) / 15, (33 : ℤ)), ((25 : ℝ) / 24, (26 : ℤ)), ((81 : ℝ) / 80, (13 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_16_15).1, (log_16_15).2, (log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((729 : ℕ) : ℝ) = ([((25 : ℝ) / 24, (2 : ℤ)), ((81 : ℝ) / 80, (-2 : ℤ)), ((126 : ℝ) / 125, (2 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]
  · dsimp only
    have e : ((784 : ℕ) : ℝ) / ((756 : ℕ) : ℝ) = ([((25 : ℝ) / 24, (1 : ℤ)), ((81 : ℝ) / 80, (-1 : ℤ)), ((126 : ℝ) / 125, (1 : ℤ))].map fun p => p.1 ^ p.2).prod := by
      norm_num
    rw [e, log_list _ (by norm_num)]
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, cxHlo, cxHhi]
    push_cast
    constructor <;> linarith [(log_25_24).1, (log_25_24).2, (log_81_80).1, (log_81_80).2, (log_126_125).1, (log_126_125).2]

set_option maxHeartbeats 20000000 in
/-- complex network: the rational side conditions of `term_le` and `le_term` -/
theorem cx_hints : ∀ r ∈ cxRows, 0 < r.1 ∧ r.1 < 784 ∧ 0 ≤ cxHlo r.1 ∧
    aC * cxHhi r.1 ≤ 1 ∧ P4 (aC * cxHhi r.1) ≤ cxU r.1 ∧
    cxD r.1 ≤ S5 ((aC + 1 / 10000000) * cxHlo r.1) := by
  intro r hr
  simp only [cxRows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> norm_num [cxHlo, cxHhi, cxU, cxD, aC, P4, S5]

/-- complex network: `Φ(a) < 1`, the source's moment test -/
theorem cx_moment : Φ 784 537696432 cxRows (aC : ℝ) < 1 := by
  apply moment_lt_one (U := fun t => (cxU t : ℝ)) (by norm_num)
  · intro r hr
    obtain ⟨h0, hm, -, h1, h2, -⟩ := cx_hints r hr
    exact term_le (by exact_mod_cast h0) (by exact_mod_cast hm.le) (by norm_num [aC])
      (cx_logs r hr).2 (by exact_mod_cast h1) (by unfold P4 at h2; exact_mod_cast h2)
  · simp only [cxRows, cxU, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num

/-- negative control: `Φ(a + 1 / 10000000) > 1`, so the moment test is tight -/
theorem cx_moment_tight : 1 < Φ 784 537696432 cxRows ((aC : ℝ) + 1 / 10000000) := by
  rw [show (aC : ℝ) + 1 / 10000000 = ((aC + 1 / 10000000 : ℚ) : ℝ) by push_cast; ring]
  apply one_lt_moment (D := fun t => (cxD t : ℝ)) (by norm_num)
  · intro r hr
    obtain ⟨h0, hm, hl, -, -, h3⟩ := cx_hints r hr
    exact le_term (by exact_mod_cast h0) (by exact_mod_cast hm.le) (by norm_num [aC])
      (cx_logs r hr).1 (by exact_mod_cast hl) (by unfold S5 at h3; exact_mod_cast h3)
  · simp only [cxRows, cxD, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num

/-! ## B. Finite bridge (`balanced_assembly.py`, `validate_bridge`) -/

/-- `halving_degree(m, child)`: the least `d ≥ 1` with `m^d > 2·child^d` -/
def IsHalvingDegree (m child d : ℕ) : Prop :=
  1 ≤ d ∧ 2 * child ^ d < m ^ d ∧ ∀ k, 1 ≤ k → k < d → m ^ k ≤ 2 * child ^ k

theorem bit_halving : IsHalvingDegree 575 529 9 := by
  refine ⟨by norm_num, by norm_num, fun k h1 h2 => ?_⟩
  interval_cases k <;> norm_num

theorem cx_halving : IsHalvingDegree 784 756 20 := by
  refine ⟨by norm_num, by norm_num, fun k h1 h2 => ?_⟩
  interval_cases k <;> norm_num

/-- `W.bit_length()` for both networks, and the largest child of each row list -/
theorem wire_bits : 2 ^ 27 ≤ 137151806 ∧ 137151806 < 2 ^ 28 ∧
    2 ^ 29 ≤ 537696432 ∧ 537696432 < 2 ^ 30 ∧
    (bitRows.map Prod.fst).max? = some 529 ∧
    (cxRows.map Prod.fst).max? = some 756 := by
  refine ⟨by norm_num, by norm_num, by norm_num, by norm_num, by decide, by decide⟩

/-- rank mass: `Σ t n_t = s`, with `s_b = W m - N + L` (copied centres) -/
theorem rank_mass : (bitRows.map fun r => r.1 * r.2).sum = 137151806 * 575 - 4073300 + 2226400 ∧
    (cxRows.map fun r => r.1 * r.2).sum = 421548223824 := by
  constructor <;> decide

def mC : ℕ := 784
def WC : ℕ := 537696432
def childC : ℕ := 756
def sC : ℕ := 421548223824
/-- `scalar_group_upper`: supplied by the producer, not recomputed (as in the script) -/
def scalar : ℕ := 4793351472
def E : ℕ := 64 * (WC + mC + scalar + 1) ^ 3
def Bs : ℕ := sC + E
def literal : ℕ := 2 * scalar * WC ^ 2 + 8 * sC + 4 * WC + 4 + 32 * mC
def C0 : ℕ := 32 * mC * Bs ^ 2
def inductionGap : ℤ := 2 * Bs * (mC - childC : ℤ) - (sC + E)
def coefficient : ℕ := 9 * 28 + 20 * 30
def degree : ℕ := 2000
def degreeGap : ℚ := degree - 51 / 25 * coefficient

/-- the semantic constants and row constants, with the script's three requirements -/
theorem semantic_values : E = 9696565176891520488192506033216 ∧ Bs = 9696565176891520488614054257040 ∧
    literal = 2771683137698171397039558468 ∧ C0 = 2358858462850846165593256368932965330169899180021667007021321420800 ∧
    E - literal = 9693793493753822316795466474748 ∧ inductionGap = 533311084729033626873772984137200 ∧
    coefficient = 852 ∧ degreeGap = 6548 / 25 ∧
    literal < E ∧ 0 ≤ inductionGap ∧ 2 * Bs + 18 < C0 ∧ 0 < sC ∧ sC < mC * WC ∧ 0 < degreeGap := by
  norm_num [E, Bs, literal, C0, inductionGap, coefficient, degree, degreeGap, mC, WC, childC, sC, scalar]

/-! ## C. Assembly (`balanced_assembly.py`, `assembly`) -/

def κ : ℚ := 25508460085039 / 500000000000000000
def β : ℚ := 1 / 20
def hB : ℚ := 1 / 1000000000000000000
def τ : ℚ := 1 - aB
def σ : ℚ := 1 - aC
def q : ℚ := aB * (1 - 2 * hB)
def lp : ℚ := 1 - q
def c : ℚ := q + hB / 4
def ε : ℚ := (1 - hB) / (1 + q)
def lam : ℚ := (τ + lp) / 2
def G : ℚ := ε * q
def r : ℚ := (G + 1 - ε) / 2
def δ : ℚ := hB / 8
def C1 : ℚ := 1
def internal : ℚ := τ + (1 - β) * max (σ - τ) 0
def leaf : ℚ := σ + β * (1 - σ)
def g1 : ℚ := 1 - ε
def g2 : ℚ := aB
def g3 : ℚ := G
def g4 : ℚ := aB
def g5 : ℚ := min (1 - ε - δ) (r - δ)
def g6 : ℚ := 1 - ε - δ
def g7 : ℚ := ε

/-- the seven margins, in the script's order -/
def margins : List (String × ℚ) := [("g1", g1), ("g2", g2), ("g3", g3), ("g4", g4), ("g5", g5), ("g6", g6), ("g7", g7)]

/-- the 47 strict slacks, in the script's order -/
def slacks : List (String × ℚ) := [
  ("a_positive", aB),
  ("a_below_b", aC - aB),
  ("b_below_one_over32", 1 / 32 - aC),
  ("beta_positive", β),
  ("beta_below_one", 1 - β),
  ("phase_leaf_above_bit", (1 - β) * aC - aB),
  ("q_positive", q),
  ("q_below_internal", 1 - internal - q),
  ("q_below_leaf", 1 - leaf - q),
  ("c_positive", c),
  ("c_below_one", 1 - c),
  ("q_below_reservations", c - q),
  ("lambda_above_tau", lam - τ),
  ("lambda_above_sigma", lam - σ),
  ("lambda_above_internal", lam - internal),
  ("lambda_prime_above_lambda", lp - lam),
  ("compact_leaf", lp - leaf),
  ("compact_reservations", lp - (1 - c)),
  ("lambda_prime_below_one", q),
  ("epsilon_positive", ε),
  ("epsilon_below_one", 1 - ε),
  ("guard_width", 1 - ε * C1),
  ("K_geometry", 1 - ε * (1 + c)),
  ("K_dominates_log", ε * c),
  ("record_suffix", 1 - ε),
  ("phase_local", 1 - ε - δ),
  ("phase_boundary", r - δ),
  ("gamma_sublinear", 1 - ε - r),
  ("cell_above_band", ε - (1 - r) / 2),
  ("prime_interval_packing", 1 - ε),
  ("alpha_positive", r),
  ("alpha_below_one", 1 - r),
  ("alpha_below_one_fourth", 1 / 4 - r),
  ("delta_positive", δ),
  ("delta_below_one_eighth", 1 / 8 - δ),
  ("short_record_fallback", ε - aB),
  ("small_field_exposure", 1 - ε - G),
  ("artificial_boundary", 8 - ε + r - δ - G),
  ("literal_scalar_guard", (E : ℚ) - literal),
  ("row_product_gap", degreeGap),
  ("g1_above_kappa", g1 - κ),
  ("g2_above_kappa", g2 - κ),
  ("g3_above_kappa", g3 - κ),
  ("g4_above_kappa", g4 - κ),
  ("g5_above_kappa", g5 - κ),
  ("g6_above_kappa", g6 - κ),
  ("g7_above_kappa", g7 - κ)]

/-- every parameter equals the certificate's value -/
theorem parameter_values : τ = 1999897960953941977 / 2000000000000000000 ∧
    σ = 9999283 / 10000000 ∧
    q = 51019523029011499897960953941977 / 1000000000000000000000000000000000000 ∧
    c = 51019523029011749897960953941977 / 1000000000000000000000000000000000000 ∧
    ε = 999999999999999999000000000000000000 / 1000051019523029011499897960953941977 ∧
    lam = 1999897960953941977000102039046058023 / 2000000000000000000000000000000000000 ∧
    lp = 999948980476970988500102039046058023 / 1000000000000000000000000000000000000 ∧
    r = 102039046058023999744902384854942500102039046058023 / 2000102039046058022999795921907883954000000000000000000 ∧
    δ = 1 / 8000000000000000000 ∧
    κ = 25508460085039 / 500000000000000000 := by
  norm_num [max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7]

/-- every slack equals the certificate's value -/
theorem slack_values : slacks = [
  ("a_positive", 102039046058023 / 2000000000000000000),
  ("a_below_b", 41360953941977 / 2000000000000000000),
  ("b_below_one_over32", 311783 / 10000000),
  ("beta_positive", 1 / 20),
  ("beta_below_one", 19 / 20),
  ("phase_leaf_above_bit", 34190953941977 / 2000000000000000000),
  ("q_positive", 51019523029011499897960953941977 / 1000000000000000000000000000000000000),
  ("q_below_internal", 102039046058023 / 1000000000000000000000000000000000000),
  ("q_below_leaf", 17095476970988500102039046058023 / 1000000000000000000000000000000000000),
  ("c_positive", 51019523029011749897960953941977 / 1000000000000000000000000000000000000),
  ("c_below_one", 999948980476970988250102039046058023 / 1000000000000000000000000000000000000),
  ("q_below_reservations", 1 / 4000000000000000000),
  ("lambda_above_tau", 102039046058023 / 2000000000000000000000000000000000000),
  ("lambda_above_sigma", 41360953941977000102039046058023 / 2000000000000000000000000000000000000),
  ("lambda_above_internal", 102039046058023 / 2000000000000000000000000000000000000),
  ("lambda_prime_above_lambda", 102039046058023 / 2000000000000000000000000000000000000),
  ("compact_leaf", 17095476970988500102039046058023 / 1000000000000000000000000000000000000),
  ("compact_reservations", 1 / 4000000000000000000),
  ("lambda_prime_below_one", 51019523029011499897960953941977 / 1000000000000000000000000000000000000),
  ("epsilon_positive", 999999999999999999000000000000000000 / 1000051019523029011499897960953941977),
  ("epsilon_below_one", 51019523029012499897960953941977 / 1000051019523029011499897960953941977),
  ("guard_width", 51019523029012499897960953941977 / 1000051019523029011499897960953941977),
  ("K_geometry", 750051019523029011749897960953941977 / 1000051019523029011499897960953941977000000000000000000),
  ("K_dominates_log", 51019523029011749846941430912965250102039046058023 / 1000051019523029011499897960953941977000000000000000000),
  ("record_suffix", 51019523029012499897960953941977 / 1000051019523029011499897960953941977),
  ("phase_local", 408156184232098999132668108506804500102039046058023 / 8000408156184232091999183687631535816000000000000000000),
  ("phase_boundary", 81631236846418999785718003278151700102039046058023 / 1600081631236846418399836737526307163200000000000000000),
  ("gamma_sublinear", 1 / 2000000000000000000),
  ("cell_above_band", 1999999999999999996999948980476970988500102039046058023 / 4000204078092116045999591843815767908000000000000000000),
  ("prime_interval_packing", 51019523029012499897960953941977 / 1000051019523029011499897960953941977),
  ("alpha_positive", 102039046058023999744902384854942500102039046058023 / 2000102039046058022999795921907883954000000000000000000),
  ("alpha_below_one", 1999999999999999999000051019523029011499897960953941977 / 2000102039046058022999795921907883954000000000000000000),
  ("alpha_below_one_fourth", 499923470715456481750204078092116045999897960953941977 / 2000102039046058022999795921907883954000000000000000000),
  ("delta_positive", 1 / 8000000000000000000),
  ("delta_below_one_eighth", 999999999999999999 / 8000000000000000000),
  ("short_record_fallback", 1999897955747958514784330442670632655931339135482668529 / 2000102039046058022999795921907883954000000000000000000),
  ("small_field_exposure", 1 / 1000000000000000000),
  ("artificial_boundary", 56003265249473856746993622559621373562499693882861825931 / 8000408156184232091999183687631535816000000000000000000),
  ("literal_scalar_guard", 9693793493753822316795466474748),
  ("row_product_gap", 6548 / 25),
  ("g1_above_kappa", 506681076925720973486535812308217897 / 500025509761514505749948980476970988500000000000000000),
  ("g2_above_kappa", 5205717867 / 2000000000000000000),
  ("g3_above_kappa", 13311134328412935473173663662493817 / 1000051019523029011499897960953941977000000000000000000),
  ("g4_above_kappa", 5205717867 / 2000000000000000000),
  ("g5_above_kappa", 3106642133196390518285083192161776467 / 8000408156184232091999183687631535816000000000000000000),
  ("g6_above_kappa", 11370953938061610502855480057564071 / 12800653049894771347198693900210457305600000000000000),
  ("g7_above_kappa", 499974490238485493756732096448749984986535812308217897 / 500025509761514505749948980476970988500000000000000000)] := by
  simp only [slacks, max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7, E, literal, WC, mC, sC, scalar, degreeGap, degree, coefficient]
  norm_num

/-- every margin equals the certificate's value -/
theorem margin_values : margins = [("g1", 51019523029012499897960953941977 / 1000051019523029011499897960953941977), ("g2", 102039046058023 / 2000000000000000000), ("g3", 51019523029011499846941430912965500102039046058023 / 1000051019523029011499897960953941977000000000000000000), ("g4", 102039046058023 / 2000000000000000000), ("g5", 81631236846418999785718003278151700102039046058023 / 1600081631236846418399836737526307163200000000000000000), ("g6", 408156184232098999132668108506804500102039046058023 / 8000408156184232091999183687631535816000000000000000000), ("g7", 999999999999999999000000000000000000 / 1000051019523029011499897960953941977)] := by
  simp only [margins, max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7]
  norm_num

theorem slacks_length : slacks.length = 47 ∧ margins.length = 7 := ⟨rfl, rfl⟩

/-- all 47 slacks are positive -/
theorem slacks_pos : ∀ s ∈ slacks, 0 < s.2 := by
  rw [slack_values]
  simp only [List.mem_cons, List.not_mem_nil, or_false]
  rintro s (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;> norm_num

/-- the minimum margin is `G = εq`, and `κ < G` -/
theorem kappa_below_margins : (∀ g ∈ margins, G ≤ g.2) ∧ ("g3", G) ∈ margins ∧ κ < G := by
  refine ⟨?_, by simp [margins, g3], ?_⟩
  · rw [margin_values]; simp only [List.mem_cons, List.not_mem_nil, or_false]
    rintro g (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;> norm_num [max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7]
  · norm_num [max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7, max_def, min_def]

/-- the script's balanced identities -/
theorem balanced_identities : 1 - ε - G = hB ∧ 1 - ε - r = hB / 2 ∧
    1 - ε * (1 + c) = hB - ε * hB / 4 := by
  norm_num [max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7]

/-- κ against the published witness, its old scoped limit, the new scoped limit and `2⁻¹⁵`;
the absorption gap; negative control: the next κ grid value fails `g3` -/
theorem kappa_facts : (5101691 / 100000000000 : ℚ) < κ ∧
    (39859 / 781289859 : ℚ) < κ ∧ κ < aB / (1 + aB) ∧
    aB / (1 + aB) = 102039046058023 / 2000102039046058023 ∧ (1 : ℚ) / 2 ^ 15 < κ ∧
    G - κ = 13311134328412935473173663662493817 / 1000051019523029011499897960953941977000000000000000000 ∧ G < κ + 1 / 500000000000000000 := by
  norm_num [max_def, min_def, aB, aC, κ, β, hB, τ, σ, q, lp, c, ε, lam, G, r, δ, C1, internal, leaf, g1, g2, g3, g4, g5, g6, g7]

/-- **The selected certificate.** Both moments hold as real inequalities at the savings
the slacks use (`τ = 1 - a_b`, `σ = 1 - a_c`), all 47 slacks are positive and `κ` lies
below every margin. -/
theorem selected_certificate : Φ 575 137151806 bitRows (aB : ℝ) < 1 ∧
    Φ 784 537696432 cxRows (aC : ℝ) < 1 ∧ τ = 1 - aB ∧ σ = 1 - aC ∧
    (∀ s ∈ slacks, 0 < s.2) ∧ ∀ g ∈ margins, κ < g.2 := by
  refine ⟨bit_moment, cx_moment, rfl, rfl, slacks_pos, fun g hg => ?_⟩
  exact lt_of_lt_of_le kappa_below_margins.2.2 (kappa_below_margins.1 g hg)

end KappaCheck.Selected
